services:
  db:
    container_name: db
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  mock_server:
    container_name: mock_server
    restart: always
    build:
      context: .
      dockerfile: dockerization/mock_server/Dockerfile
    env_file:
      - mock_server/.env
    ports:
      - '8001:8000'
    depends_on:
      - db

