"""02_add_account_to_card

Revision ID: 09f9484d771f
Revises: 50d3cf342a4b
Create Date: 2023-09-25 18:00:58.706805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f9484d771f'
down_revision = '50d3cf342a4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('account_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cards', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'account_id')
    # ### end Alembic commands ###
