"""03_add_time_to_transactio

Revision ID: 7a46f6e1beb3
Revises: 3cb876ffa653
Create Date: 2023-09-21 18:18:33.489436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a46f6e1beb3'
down_revision = '3cb876ffa653'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'time')
    # ### end Alembic commands ###
