"""04_unique_cashback

Revision ID: 9763a556df3b
Revises: 97eddf45b79f
Create Date: 2023-10-12 18:58:52.595206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9763a556df3b'
down_revision = '97eddf45b79f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cashbacks', ['product_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cashbacks', type_='unique')
    # ### end Alembic commands ###
