"""07_add_limit_value

Revision ID: 3563e668c32e
Revises: d8caff8a2f48
Create Date: 2023-12-02 14:07:41.956043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3563e668c32e'
down_revision = 'd8caff8a2f48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('limits', sa.Column('value', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('limits', 'value')
    # ### end Alembic commands ###
