"""02_user_cashback_status

Revision ID: 6e14a254c2f6
Revises: 4d0c70ef55d1
Create Date: 2023-08-28 14:04:04.786982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e14a254c2f6'
down_revision = '4d0c70ef55d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usercashbacks', sa.Column('status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usercashbacks', 'status')
    # ### end Alembic commands ###
