"""04_add_account_transactions_time_update

Revision ID: 8ba0bee7789c
Revises: a672b04cf8d2
Create Date: 2023-09-27 20:31:00.088214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ba0bee7789c'
down_revision = 'a672b04cf8d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('last_transation_time', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('accounts', sa.Column('transations_update_time', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column('accounts', 'last_transations_update')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('last_transations_update', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('accounts', 'transations_update_time')
    op.drop_column('accounts', 'last_transation_time')
    # ### end Alembic commands ###
