"""03_add_cards_to_account

Revision ID: a672b04cf8d2
Revises: b149f8dd2005
Create Date: 2023-09-27 10:51:13.317422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a672b04cf8d2'
down_revision = 'b149f8dd2005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
