"""02_add_account_to_card

Revision ID: b149f8dd2005
Revises: 0deefc17f5fe
Create Date: 2023-09-26 20:52:05.609247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b149f8dd2005'
down_revision = '0deefc17f5fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('account_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cards', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'account_id')
    # ### end Alembic commands ###
