"""05_unique_cashback

Revision ID: ee4c58a7312f
Revises: 8ba0bee7789c
Create Date: 2023-10-12 19:43:13.320813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee4c58a7312f'
down_revision = '8ba0bee7789c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cashbacks', ['product_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cashbacks', type_='unique')
    # ### end Alembic commands ###
